#!/bin/bash
#
# run /bin/ls many times, with a lot of spaces everywhere

command="ls
ls --color=auto -a
pwd
le"

OLDPATH="$PATH"
PATH="$PATH"
#$ECHO "env" 

echo "$command" | valgrind ./hsh

# put PATH back
PATH="$OLDPATH"

# wait a little bi

# check the result
